### PR TITLE
Jquery

### PR DESCRIPTION
**Pull request by CosmicWebServices**
I am ready to merge

### CODE REVIEW

**Comment by JordanB-1337** [comment]
Hi CosmicWebServices, this repository isn't what's being shown on the website. I'm not really sure what the plan is for this repo though. Should I PM you our website FTP on gitter? (It's currently unviewable due to some epic fails to make the site HTTPS)

**Comment by CosmicWebServices** [comment]
Well this makes base.js jQuery so it is more cross-browser

**Comment by JordanB-1337** [comment]
"Hi CosmicWebServices, this repository isn't what's being shown on the website. "

**Comment by CosmicWebServices** [comment]
I know

**Comment by JordanB-1337** [comment]
Then why are you committing here not there?

**Comment by CosmicWebServices** [comment]
This is for the player

**Comment by JordanB-1337** [comment]
The player is part of the website. and the player is somewhere else now.

**Pull request closed without merging**
